resources/print.css
resources/screen-common.less

Word breaks should not be used for Korean text.
- https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
- https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

screen-common.less: Use 'word-break: keep-all'

---

resources/skins.femiwiki/elements.less
resources/variables.less

Currently the stylesheet applies Korean fonts to every text, which is particularly bad for Japanese text on Windows (since Malgun Gothic supports Kana). This makes sure texts marked as `[lang=ja]` get a proper Japanese font.
Closes #228

Define font-family for `[lang=ja]`

---

resources/skins.femiwiki.moduleSkinStyles/ext.uls.preferencespage.less
resources/skins.femiwiki.moduleSkinStyles/ext.visualEditor.mwimage.less
resources/skins.femiwiki.moduleSkinStyles/mediawiki.action.view.postEdit.less
resources/variables.less
skin.json

- Removes padding of `.mwhighlight > pre`. (Closes https://github.com/femiwiki/FemiwikiSkin/issues/245)
- Makes postEdit notification centered evenly. (Closes https://github.com/femiwiki/FemiwikiSkin/issues/45)
- Fixes blue link for ULS in Special:Preferences. (Closes https://github.com/femiwiki/FemiwikiSkin/issues/244)
- Fixes blue link to description page in media settings. (Closes https://github.com/femiwiki/FemiwikiSkin/issues/247)

Minor bug fixes

---

.prettierignore
includes/Hooks.php
includes/templates/Header.mustache
resources/@types/mediawiki.d.ts
resources/skins.femiwiki.js/discussionStatus.js
resources/skins.femiwiki.js/skin.js
resources/skins.femiwiki.js/watchingUsers.js
resources/skins.femiwiki/images/speechBubbles-ltr-new.svg
resources/skins.femiwiki/images/speechBubbles-rtl-new.svg
resources/skins.femiwiki/interface.less
resources/variables.less
skin.json

- Uses icons for namespaces and watch/unwatch navigations.
- Moves navigations below the first heading.
- Makes black icons less dark as they are not important than headings.
- Shows numbers follow the discussion and watch.
- Shows the watch action to anonymous users to encourage signing-ups.
| Previous | This patch makes |
|--|--|
| ![image](https://user-images.githubusercontent.com/28209361/124206206-dc361b00-db1d-11eb-8a3e-c45b97de4a2e.png) | ![image](https://user-images.githubusercontent.com/28209361/124206178-c9bbe180-db1d-11eb-87bb-fb713f532a96.png) |

Improve the header of the article

---

resources/skins.femiwiki.moduleSkinStyles/ext.relatedArticles.cards.less
resources/variables.less

Replaces underline of links with `border-bottom` which is more customizable.
Closes #15.

Replace underline of links with border-bottom

---

skin.json

In 1.37 support was added for declaring template directory relative
to skin. Relative to core is deprecated in 1.37, will likely be removed
in 1.39

Template directory should be relative to skin

---

resources/skins.femiwiki/contents.less

Make the label for category use single line

---

resources/skins.femiwiki/interface.less

The margin-bottom previously used was added to the height of the footer, but the height did not include its children; making the actual margin arbitrary.
Previous:
This changes it to:

Use exact padding for the bottom of the footer

---

resources/skins.femiwiki.moduleSkinStyles/ext.DarkMode.styles.less

Set explicit background-color of body element and html element to prepare the inversion by DarkMode.
Thanks to @saschanaz for reporting this bug and identiying the ticket of the bug on Firefox.
Fixes #397

darkmode: Set background-color of body and html

---

resources/skins.femiwiki/interface.less

Resolves that Special:Search has a misaligned footer.

Do not hide the content of the footer; Apply the child ul

---

includes/Hooks.php
includes/SmallElementsHooks.php
skin.json

Hey there! I'm getting setup with Femiwiki locally (lots of great stuff happening here - thank you for innovating!!!)
However, with FemiWiki installed I can't currently run MediaWiki integration tests (phpunit). This happens because of the class unconditionally added in this hook so I need some way to turn this off. Hope this patch is acceptable!

Feature flag link class

---

resources/@types/CheckboxHack.d.ts
resources/skins.femiwiki.js/skin.js

https://gerrit.wikimedia.org/g/mediawiki/core/+/ae82334289ff47a9e9c6dfd0dc2ad292d726d3f6/HISTORY#691:
```
* The `button` parameter for `bindUpdateAriaExpandedOnInput` and
`updateAriaExpanded` in checkboxHack.js have been deprecated.
`bindToggleOnSpaceEnter` has also been deprecated in favor of
`bindToggleOnEnter`.
```

Replace the deprecated usages of checkboxhack

---

skin.json

The alias ResourceLoaderSkinModule was dropped in favor of MediaWiki\\ResourceLoader\\SkinModule in
https://gerrit.wikimedia.org/r/c/mediawiki/core/+/994854
See: https://phabricator.wikimedia.org/T356563

Fixes Class 'ResourceLoaderSkinModule' Not Found Error

---

resources/variables.less

Fixes this:
```
Error: [exception] [error] [{reqId}] {exception_url}   Less_Exception_Compiler: error evaluating function `rgba` color functions take numbers as parameters index: 1965 in variables.less on line 61, column 1
59| 
60| // Same colors as Codex's @background-color-button-quiet--*
61| @button-background-color--hover: rgba(0, 24, 73, 7/255);
62| @button-background-color--active: rgba(0, 36, 73, 21/255);
63| 
64| @opacity-icon: 65%; {"exception":{"currentFile":{"entryPath":"\/workspace\/src\/skins\/Femiwiki\/resources\/skins.femiwiki.moduleSkinStyles\/","entryUri":"\/workspace\/src\/skins\/Femiwiki\/resources\/skins.femiwiki.moduleSkinStyles\/","rootpath":"\/workspace\/src\/skins\/Femiwiki\/resources\/skins.femiwiki.moduleSkinStyles\/","currentDirectory":"\/workspace\/src\/skins\/F …
```

fix: avoid fraction expression in Less

---

resources/skins.femiwiki/interface.less

The result:
and it was previously:

fix: Don't depend on the icon file from MediaWiki core

---

.gitignore
.prettierignore
README.md
dev.js
package-lock.json
package.json

```bash
npm i
npm run dev
```
This requires internet access and approximal 500MB on your disk. Under the hood, `run run dev` downloads and launches a MediaWiki instance and a Web server with PHP. ([FrankenPHP](https://frankenphp.dev/))

chore(development): Add `npm run dev` command

---

tests/selenium/package.json

#803 이후로 최상위 경로에 `type: module`이 추가되었으나, ESM 지원은 wdio 8 에서 추가되었으므로 7을 쓰는 지금은 CJS로 선언해둘 필요가 있습니다.
현재 실패 중인 selenium 테스트를 고칩니다.

chore(tests/selenium): declare as commonjs

---

.github/workflows/extension-test.yml

We have a JS dependency(https://github.com/xpressengine/XEIcon) some PHPUnit tests depend on. This is uncommon in the MediaWiki skin ecosystem, so manual installation required.

chore(tests/phpunit): install npm always

---

resources/skins.femiwiki/interface.less

Fixes this:
Overwrites https://gerrit.wikimedia.org/g/mediawiki/core/+/e6e72357d263969715ff6bcd6c361b83257b029e/resources/src/mediawiki.helplink/helplink.less#4

fix: Helplink

---

resources/variables.less

Fixes #792
Desktop:
Mobile:
Desktop:
Mobile:

fix(styles): Cleanup thumb image
