femiwiki/FemiwikiSkin

resources/print.css
resources/screen-bbs.less
resources/screen-category.less
resources/screen-changes.less
resources/screen-common.less
resources/screen-dialog.less
resources/screen-flow.less
resources/screen-gnb.less
resources/screen-table.less
resources/variables.less

https://www.mediawiki.org/wiki/Manual:Coding_conventions/CSS

Lens0021 patch code cleaning

---

resources/skins.femiwiki.share/mw.fw.ShareDialog.js

트위터/페이스북 로고 뒤바뀐것 바로잡음

---

resources/screen-common.less

Closes https://github.com/femiwiki/FemiwikiSkin/issues/110

Add bottom border to h2, h3 headings

---

resources/screen-common.less

FlaggedRevs tweaks

---

resources/screen-common.less

CSS: Remove height of select

---

package-lock.json
package.json

* https://npmjs.com/advisories/1179

build: Updating minimist to 1.2.5

---

skin.json

Improve phpcs to use mediawiki-codesniffer rules

Specify required MW version

---

.github/workflows/submit-patch.yml
.github/workflows/upload-release.yml
skin.json

Related to https://github.com/femiwiki/femiwiki/issues/200

build: Change releasing steps

---

i18n/en.json
i18n/qqq.json
includes/FemiwikiTemplate.php
includes/SkinFemiwiki.php
includes/SkinFemiwikiHooks.php
package.json
resources/skins.femiwiki/interface.less
skin.json
yarn.lock

<details>
<summary>previous</summary>
</details>

Add Xeicon to personal tools

---

i18n/en.json
i18n/ko.json
i18n/qqq.json
includes/SkinFemiwikiHooks.php
resources/@types/mediawiki.d.ts
resources/@types/oo.d.ts
resources/skins.femiwiki.mobile/init.js
skin.json

mobile: Add a switch function to edit buttons

---

resources/skins.femiwiki/contents.less

Replace deprecated ID with class

---

resources/skins.femiwiki.moduleSkinStyles/ext.echo.ui.less
resources/skins.femiwiki/elements.less
resources/skins.femiwiki/interface.less
resources/variables.less

| Before | After |
|--|--|
| ![image](https://user-images.githubusercontent.com/28209361/124689916-5a2a6580-df14-11eb-8083-44a10918dacb.png) | ![image](https://user-images.githubusercontent.com/28209361/124689942-64e4fa80-df14-11eb-943a-29cce8dee82f.png) |

Fix bad text wrapping in menu items

---

resources/skins.femiwiki.moduleSkinStyles/ext.flow.styles.base.less
resources/variables.less

| Before | After | 
|--|--|
| ![image](https://user-images.githubusercontent.com/28209361/126937383-b1a3247e-f1a6-4a10-a2b5-46fa03f476d2.png) | ![image](https://user-images.githubusercontent.com/28209361/126937422-28cb00be-96e7-42c6-afe8-31b7e0b8df22.png) |

Add paddings to the syntaxhighlight box w/o line numbers

---

includes/SkinFemiwiki.php

Use User->isRegistered(), not deprecated isLoggedIn()

---

includes/SkinFemiwiki.php

Generate ID when none given

---

includes/SmallElementsHooks.php
skin.json

Related to https://github.com/femiwiki/FemiwikiSkin/issues/14

Add a body class when the small-elements feature is enabled

---

package.json
yarn.lock

Fixes broken tests. I have no idea why the test of #305 has passed.

Downgrade @types/node-fetch to 2.5.12

---

resources/skins.femiwiki.moduleSkinStyles/ext.facetedCategory.less
resources/skins.femiwiki.moduleSkinStyles/ext.visualEditor.desktopTarget.less
resources/skins.femiwiki.moduleSkinStyles/mediawiki.action.edit.styles.less
resources/skins.femiwiki/contents.less
resources/skins.femiwiki/interface.less
resources/variables.less
skin.json

Follows https://github.com/femiwiki/FacetedCategory/pull/152

Improve the support of FacetedCategory

---

resources/skins.femiwiki.moduleSkinStyles/ext.flow.styles.base.less
resources/variables.less

Fix pre style

---

resources/skins.femiwiki.moduleSkinStyles/ext.flow.styles.base.less
resources/variables.less

[1_36] Fix pre style

---

includes/SkinFemiwiki.php
resources/skins.femiwiki.moduleSkinStyles/ext.facetedCategory.less
resources/skins.femiwiki.moduleSkinStyles/ext.flow.styles.base.less
resources/skins.femiwiki.moduleSkinStyles/ext.visualEditor.desktopTarget.less
resources/skins.femiwiki.moduleSkinStyles/mediawiki.action.edit.styles.less
resources/skins.femiwiki/contents.less
resources/skins.femiwiki/interface.less
resources/variables.less
skin.json

Backport for REL1_37

---

package.json
yarn.lock

https://github.com/femiwiki/FemiwikiSkin/pull/313#pullrequestreview-758419567 에서 뭐가 false-positive인지 안보여서 만듦
> The npm-test is failed accoding to the log. The result is false-positive.
>
> _Originally posted by @lens0021 in https://github.com/femiwiki/FemiwikiSkin/pull/313#pullrequestreview-758419567_

Use @types/node-fetch v3

---

resources/skins.femiwiki.moduleSkinStyles/mediawiki.action.view.postEdit.less
skin.json

https://github.com/femiwiki/FemiwikiSkin/issues/45 is fixed in the core itself as https://phabricator.wikimedia.org/T284048.

Remove workaround fixed in the core

---

CHANGELOG.md
resources/skins.femiwiki.moduleSkinStyles/ext.flow.styles.base.less

Backport of 8cf64c6c4c493f8adfc5da67d7a5f879d97cb737

Add the missing comma

---

resources/skins.femiwiki.moduleSkinStyles/ext.dismissableSiteNotice.styles.less
skin.json

Add module style for DismissableSiteNotice

---

CHANGELOG.md
resources/skins.femiwiki.moduleSkinStyles/ext.echo.ui.less

(cherry picked from commit 80c3d590f290a41e53e3d5feb569de8de958f0a2)

Add styles for clipped Echo popup

---

CHANGELOG.md
resources/skins.femiwiki.moduleSkinStyles/mediawiki.rcfilters.filters.base.styles.less
skin.json

Closes https://github.com/femiwiki/FemiwikiSkin/issues/385
(cherry picked from commit eeab0da107bf5261334bca88f8ac2f630888eaa5)

Fix the blue spinner on Special:RecentChanges

---

CHANGELOG.md
resources/skins.femiwiki/contents.less

(cherry picked from commit 8eee484ed7d6f3176239285c3dc5827fc3a31ea5)

Make the label for category use single line

---

includes/SkinFemiwiki.php
includes/SmallElementsHooks.php

Use getBoolOption() instead of getOption()

---

resources/skins.femiwiki/interface.less

Use exact padding for the bottom of the footer

---

resources/skins.femiwiki.moduleSkinStyles/ext.DarkMode.styles.less
skin.json

- Remove the background of tables; it stands out too much.
- Override the explicit blue color of links. (Closes #396)

Add skin style for DarkMode

---

resources/skins.femiwiki/interface.less

Backport of https://github.com/femiwiki/FemiwikiSkin/pull/410 on REL1_37

Do not hide the content of the footer; Apply the child ul

---

resources/skins.femiwiki/contents.less

Fix conflict between DarkMode and RelatedArticles

---

resources/skins.femiwiki.moduleSkinStyles/ext.DarkMode.styles.less
resources/skins.femiwiki/contents.less

Move to ext.DarkMode.styles.less

---

CHANGELOG.md
resources/skins.femiwiki.moduleSkinStyles/ext.DarkMode.styles.less

Fix conflict between DarkMode and GrowthExperiments

---

.github/workflows/test.yml

Related to https://github.com/femiwiki/.github/issues/34

Use quibble-with-supervisord entrypoint

---

package.json
yarn.lock

Fetch xeicon from Github directly

---

skin.json

(cherry picked from commit a82129d90218889b0b54a5beb36eb8e5275ce4ec)

Set FemiwikiUseLargerElements on by default (#506)

---

skin.json

Orders preperties by the order of https://github.com/wikimedia/mediawiki/blob/025ff0f4a442014ab8a51affdff0147f735d7cc4/docs/extension.schema.v2.json
I belive the order is not purpose of the schema, anyway a standard has been required to me.

Reorder properties of skin.json

---

tests/selenium/wdio.conf.js

https://github.com/femiwiki/femiwiki/issues/298

selenium: run tests concurrently

---

includes/FemiwikiResourceLoaderSkinModule.php
includes/SmallElementsHooks.php
resources/skins.femiwiki/interface-gnb.less
skin.json

Note: This PR also reverts https://github.com/femiwiki/FemiwikiSkin/pull/524 which is mistakenly backported.

Append class to body always 

---

includes/templates/NavigationBar.mustache

cherry picked from https://github.com/femiwiki/FemiwikiSkin/pull/538

Avoid literals in urls in the navigation bar

---

includes/HookHandler/DefaultHooks.php

Closes #531
CC @Universal-Omega

Add type checks in HtmlPageLinkRendererBegin hook

---

resources/skins.femiwiki.moduleSkinStyles/ext.visualEditor.core.less
resources/variables.less

Add support for mw:File

---

includes/HookHandler/Portlet.php
skin.json

Remove the PersonalUrls hook

---

includes/HookHandler/Portlet.php
skin.json

Remove PersonalUrls hook

---

package.json

[Co-authored-by: femiwiki-bot <femiwiki-bot@users.noreply.github.com>](https://github.com/femiwiki/femiwiki/issues/311)

Use the REL1_39 branch of @femiwiki/ooui-femiwiki-theme

---

.phpcs.xml
composer.json

https://github.com/femiwiki/femiwiki/issues/318

Add php compatibility check

---

CHANGELOG.md
resources/skins.femiwiki.moduleSkinStyles/ext.echo.ui.less
skin.json
yarn.lock

Closes https://github.com/femiwiki/femiwiki/issues/321

Release v3.1.1: fix OOUI theme

---

resources/skins.femiwiki.moduleSkinStyles/ext.DarkMode.styles.less

Solves https://github.com/femiwiki/femiwiki/issues/324

Explicitly set the background

---

CHANGELOG.md
resources/skins.femiwiki.moduleSkinStyles/ext.DarkMode.styles.less
skin.json

Release v3.1.2

---

resources/skins.femiwiki.moduleSkinStyles/ext.DarkMode.styles.less

Fixes https://github.com/femiwiki/FemiwikiSkin/issues/653

fix: DarkMode class is changed

---

CHANGELOG.md
resources/skins.femiwiki.moduleSkinStyles/ext.DarkMode.styles.less
skin.json

fix: DarkMode Changes

---

package.json
tests/selenium/specs/echo.js
tests/selenium/userpreferences.js
yarn.lock

https://github.com/femiwiki/femiwiki/issues/299

ci: Refactor WebdriverIO tests from sync to async mode

---

resources/variables.less

Indent lower <li>s under 4 level

---

resources/variables.less

Make headers distinguishable

---

resources/variables.less

backport: Make headers distinguishable

---

resources/skins.femiwiki/elements.less

Imported from https://github.com/femiwiki/remote-gadgets/commit/c4f4d9605e436c104bbee3a0591dd7346582515b

Minify font-size on little larger mobile

---

resources/skins.femiwiki/elements.less

Minify font-size on little larger mobile devices

---

resources/skins.femiwiki.moduleSkinStyles/ext.visualEditor.desktopTarget.less

Center VE preview

---

resources/skins.femiwiki.moduleSkinStyles/ext.flaggedRevs.basic.less

Make FlaggedRevs's comment box not overflow

---

resources/variables.less

Enlarge h3 than h4

---

resources/variables.less

Backport: Enlarge h3 than h4

---

resources/variables.less

Remove boxes of 'frame'd images

---

resources/skins.femiwiki/interface.less

Show hr tag on localNotice

---

resources/skins.femiwiki.moduleSkinStyles/mediawiki.ui.button.less
skin.json

Replace 'mediawiki.ui/variables' call with skin variables

---

.github/workflows/release-and-submit.yml
package.json
yarn.lock

https://github.com/femiwiki/femiwiki/issues/342

Bump @femiwiki/ooui-femiwiki-theme

---

.github/workflows/release-and-submit.yml
CHANGELOG.md
includes/Constants.php
includes/HookHandler/DefaultHooks.php
includes/SkinFemiwiki.php
includes/templates/skin.mustache
resources/skins.femiwiki.share.ui/mw.fw.ShareDialog.js
resources/skins.femiwiki.share/init.js
resources/skins.femiwiki/interface.less
resources/variables.less
skin.json

Release v4.0.0

---

includes/SkinFemiwiki.php

Use data-last-modified text for modifiedat

---

includes/HookHandler/Portlet.php

https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Echo/+/856122

Replace the old class names of Echo

---

CHANGELOG.md
resources/skins.femiwiki.moduleSkinStyles/mobile.init.less
skin.json

Backport of https://github.com/femiwiki/FemiwikiSkin/pull/783

REL1_42: The files of mobile.init are moved

---

.github/workflows/extension-test.yml

chore(.github): set matrix for MediaWiki versions

---

dev.js

v1.5.0 is crashed on my Linux laptop.

chore(dev.js): Used a fixed version of frankenphp

---

.github/workflows/extension-test.yml

Closes https://github.com/femiwiki/quibble-action/issues/2

chore(test): upload log when quibble fails

---

.github/workflows/extension-test.yml

https://github.com/femiwiki/femiwiki/issues/387

chore(test): test MediaWiki 1.43

---

includes/SkinFemiwiki.php

fix: Use array_splice() insteaf of unsetting

---

dev.js

https://github.com/femiwiki/femiwiki/issues/387

chore(dev.js): bump MediaWiki to 1.43.1

---

resources/skins.femiwiki/elements.less

Fixes https://github.com/femiwiki/FemiwikiSkin/issues/833
fyi: The styles are added at https://github.com/femiwiki/FemiwikiSkin/issues/139

fix: remove styles of radio and checkbox

---

includes/SkinFemiwiki.php

https://github.com/femiwiki/FemiwikiSkin/pull/834#discussion_r2062528445

fix: Use 1 as the length param of array_splice

---

resources/skins.femiwiki/elements.less

Follows #840
Fixes #850
These styles were also added at #142 as #139

fix: remove more input styles

---

resources/skins.femiwiki/contents.less

fix: Restore the padding in editsection

---

resources/skins.femiwiki/contents.less

See https://github.com/wikimedia/mediawiki/commit/32f81122dc38a3b3e6991dec7aa9b3946a50bdbd

chore: Define editsection spacing in a direction aware way

---

resources/skins.femiwiki/interface.less

feat: Emphasize the edit button

---

.github/workflows/extension-test.yml

https://github.com/femiwiki/FemiwikiSkin/issues/823

chore(test/selenium): disable the test

---

i18n/isv-latn.json

chore: Localisation updates from https://translatewiki.net.

---

package-lock.json
package.json

chore(tests/selenium): upgrade to wdio 8

---

i18n/ps.json

chore(i18n): Localisation updates from https://translatewiki.net.
